[build]
command = 'npm run prod'
publish = 'public'
environment = { PHP_VERSION = "8.3" }

[[headers]]
for = '/*'
[headers.values]
Permissions-Policy = 'interest-cohort=()'

[[redirects]]
  from = "/work"
  to = "/"
  status = 302
